### ISSUE TITLE
Align Quipudocs and GUI application display name

### ISSUE THREAD

**Issue by cdcabrera** [quipucords/quipucords-ui#53]
## Feature description
As user I would like see documentation that has the same application display name as the GUI I'm viewing.

### Is your feature request related to a problem?

The GUI currently has 2 facets to its display
1. A branded version
1. A default/non-branded version

Quipudocs has 2 facets to its GUI help docs
1. QPC
2. Discovery
 
Based on the starting implementations of Quipudocs, and what is currently active on the GUI we'd like to make sure the application titles align

### Describe the solution you'd like

We'd like to nullify display label drift between docs and the GUI
___

## Acceptance Criteria
- [x] Application names should be the same between Quipudocs and the GUI

___

## Additional context

...

@bclarhk @jlprevatt @annibond

**Comment by kholdaway** [comment]
The upstream titles should be `quipucords` and the downstream should be `discovery`.  Discovery is only used downstream.

**Comment by jlprevatt** [comment]
Here is my understanding of what should be happening:

*Upstream*
- Docs use "Quipucords," "qpc," in product/code mentions. 
- unbranded UI = no RH logo on GUI splash page, banner, etc.
- GUI uses "Quipucords" product name on splash page, banner, etc.

*Downstream*
- Docs use "discovery" (and occasionally "The product discovery tool" when required by sentence construction), "dsc" in product/code mentions.
- branded UI = RH logo (iconography and name) on GUI splash page, banner, etc.
- GUI uses "discovery" (well, really "product discovery" is there now...) on splash page, banner, etc.
  - "product discovery tool"/"discovery" is a component *without* special dispensation from Branding to use capitalization for the name.
  - Because "product discovery tool"/"discovery" is a component, it *cannot* be preceded by the company name "Red Hat" in running text. (Only products get that.) So "Red Hat product discovery tool" or "Red Hat discovery" should appear *nowhere* in the docs, UI, or customer portal/marketing pages.
